kind: Service
apiVersion: v1
metadata:
  name:  load-balancer
spec:
  selector:
    run:  load-balancer-example
  type:  LoadBalancer
  ports:
  - name:  name-of-the-port
    port:  8080
    targetPort:  8080